[profile.default]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 10000
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  "solady/=lib/solady/src",
]
verbosity = 1
fs_permissions = [{ access = "read-write", path = "./static/public/json/"}]
