name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  front-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        run: npm install
      - name: Linting tests
        run: npm run lint
