name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  front-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Build Svelte Application
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "21.2.0"
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: Install deps
        run: npm install
      - name: Linting tests
        run: npm run lint
      - name: Linting tests
        run: npm run build
