name: Production

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Build Svelte Application
        uses: actions/setup-node@v3.6.0
        with:
          node-version: "21.2.0"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dev dependencies
        run: npm install

      - name: Build
        run: npm run build

    # Commit and push all changed files.
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        # Only run on main branch push (e.g. after pull request merge).
        if: github.event_name == 'push'
        run: |
          mv build /tmp
          git checkout -f build
          cp -av /tmp/build/* .
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push -f
